name: 'helmfile tool installer'
description: 'Install a specific version of the helmfile. Acceptable values are latest or any semantic version string like 0.14.0'
inputs:
  version:
    description: 'Version of helmfile'
    required: true
    default: 'latest'
outputs:
  helmfile-path:
    description: 'Path to the cached helmfile binary'
branding:
  icon: 'unlock'
  color: 'gray-dark'
runs:
  using: node16
  main: 'dist/index.js'

